language: csharp
solution: Terracord.sln

jobs:
  include:
    - dotnet: none
      mono: latest
      install:
        - nuget restore Terracord.sln
        - TMPDIR=tmp
        - mkdir $TMPDIR
        - ZIPFILE=tshock_4.3.26.zip
        - cd $TMPDIR
        - curl -fsSLJo $ZIPFILE https://github.com/Pryaxis/TShock/releases/download/v4.3.26/tshock_4.3.26.zip
        - unzip -q $ZIPFILE OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll
        - mkdir -p ../lib
        - mv OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll ../lib
      script:
        - msbuild /p:Configuration=Debug Terracord.sln
    - dotnet: 3.1.100
      mono: none
      install:
        - dotnet restore
        - TMPDIR=tmp
        - mkdir $TMPDIR
        - ZIPFILE=tshock_4.3.26.zip
        - cd $TMPDIR
        - curl -fsSLJo $ZIPFILE https://github.com/Pryaxis/TShock/releases/download/v4.3.26/tshock_4.3.26.zip
        - unzip -q $ZIPFILE OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll
        - mkdir -p ../lib
        - mv OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll ../lib
      script:
        - dotnet build -c Debug
