language: csharp
solution: Terracord.sln

jobs:
  include:
    - dotnet: none
      mono: latest
      install:
        - nuget restore Terracord.sln
        - TMPDIR=tmp
        - mkdir $TMPDIR
        - ZIPFILE=TShock4.4.0_Pre11_Terraria1.4.0.5.zip
        - cd $TMPDIR
        - curl -fsSLJo $ZIPFILE https://github.com/Pryaxis/TShock/releases/download/v4.4.0-pre11/TShock4.4.0_Pre11_Terraria1.4.0.5.zip
        - unzip -q $ZIPFILE OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll
        - mkdir -p ../lib
        - mv OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll ../lib
        - cd ..
      script:
        - msbuild /p:Configuration=Debug Terracord.sln
      after_success:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL
      after_failure:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
    - dotnet: 3.1.100
      mono: none
      install:
        - dotnet restore
        - TMPDIR=tmp
        - mkdir $TMPDIR
        - ZIPFILE=TShock4.4.0_Pre11_Terraria1.4.0.5.zip
        - cd $TMPDIR
        - curl -fsSLJo $ZIPFILE https://github.com/Pryaxis/TShock/releases/download/v4.4.0-pre11/TShock4.4.0_Pre11_Terraria1.4.0.5.zip
        - unzip -q $ZIPFILE OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll
        - mkdir -p ../lib
        - mv OTAPI.dll TerrariaServer.exe ServerPlugins/TShockAPI.dll ../lib
        - cd ..
      script:
        - dotnet build -c Debug
      after_success:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL
      after_failure:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL
