version: 0.1.{build}
image: Visual Studio 2019
platform: x86
configuration: Debug
before_build:
  - nuget restore
  - SET TEMPDIR=temp
  - SET ZIPFILE=tshock_4.3.26.zip
  - md %TEMPDIR%
  - cd %TEMPDIR%
  - curl -O https://github.com/Pryaxis/TShock/releases/download/v4.3.26/tshock_4.3.26.zip
  - echo %cd%
  - dir
  - 7z e %ZIPFILE%
