version: 0.1.{build}
image: Visual Studio 2019
platform: x86
configuration: Debug
before_build:
  - nuget restore
  - SET TEMPDIR=temp
  - SET ZIPFILE=tshock_4.3.26.zip
  - md %TEMPDIR%
  - cd %TEMPDIR%
  - curl -fsSLJo %ZIPFILE% https://github.com/Pryaxis/TShock/releases/download/v4.3.26/tshock_4.3.26.zip
  - 7z e %ZIPFILE% -o..\lib\ OTAPI.dll TerrariaServer.exe TShockAPI.dll -r
build:
  verbosity: minimal
notifications:
  - provider: Webhook
    url: WEBHOOK_URL
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
