version: 0.1.{build}
image: Visual Studio 2019
platform: x86
configuration: Debug
before_build:
  - nuget restore
  - SET ZIPLINK=https://github.com/Pryaxis/TShock/releases/download/v4.3.26/tshock_4.3.26.zip
  - SET ZIPFILE=temp\tshock_4.3.26.zip
  - curl -fsS -o %ZIPFILE% %ZIPLINK%
  - 7z e %ZIPFILE% -olib\ OTAPI.dll Terraria.exe TShockAPI.dll -r
